# Generated by Django 5.1.3 on 2025-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_city_governorate_specialtydoctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
