# Generated by Django 5.1.3 on 2025-03-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientprofile_chronic_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='certificates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
