# Generated by Django 5.1.3 on 2025-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctornurseprofile_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
