# Generated by Django 5.1.3 on 2025-04-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('users', '0007_doctornurseprofile_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='governorate',
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to='hospital.city'),
        ),
        migrations.DeleteModel(
            name='Governorate',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
