# Generated by Django 5.1.3 on 2025-05-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_city_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornurseprofile',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
