# Generated by Django 5.1.3 on 2025-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_doctornurseprofile_governorate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='city',
            field=models.CharField(default='Cairo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='governorate',
            field=models.CharField(default='Cairo Governorate', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='services',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctornurseprofile',
            name='specialty',
            field=models.CharField(default='Dermatology', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
