# Generated by Django 5.1.3 on 2025-07-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_doctornurseprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornurseprofile',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctornurseprofile',
            name='subscription_status',
            field=models.CharField(choices=[('NOT_PAID', 'لم يتم الدفع'), ('PAID', 'تم الدفع'), ('EXPIRED', 'انتهت الصلاحية'), ('CANCELLED', 'تم الالغاء'), ('PENDING', 'قيد الانتظار')], default='PENDING', max_length=20),
        ),
    ]
