# Generated by Django 5.1.3 on 2025-03-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_availableslot_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='max_bookings',
            field=models.IntegerField(default=3),
        ),
    ]
