# Generated by Django 5.1.3 on 2025-07-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cash', 'كاش في العيادة')], default='paypal', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'تم الدفع'), ('CANCELLED', 'تم الإلغاء'), ('FAILED', 'فشل الدفع')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
