# Generated by Django 5.1.3 on 2025-03-15 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_doctor_alter_chat_nurse_and_more'),
        ('users', '0004_alter_doctornurseprofile_certificates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctornurseprofile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_chats', to='users.doctornurseprofile'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('patient', 'doctor'), ('patient', 'nurse')},
        ),
    ]
