# Generated by Django 5.1.3 on 2025-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmdevice',
            name='active',
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='device_type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10),
            preserve_default=False,
        ),
    ]
