# Generated by Django 5.1.3 on 2025-06-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_fcmdevice_active_fcmdevice_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='device_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fcmdevice',
            name='registration_id',
            field=models.TextField(),
        ),
    ]
